---
# tasks file for apigee-opdk-setup-os-sysctl

- name: Update sysctl attributes for ipv6
  tags: ['ipv6']
  become: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
  with_items: "{{ sysctl_ipv6 }}"


- name: Update sysctl attributes
  become: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
  with_items: "{{ sysctl_minimum }}"

